### ISSUE TITLE
GVariant dictionnaries returned from GDBus method calls and signals are empty

### ISSUE THREAD

**Issue by tlefebvr** [lgi-devs/lgi#282]
This code should display every properties belonging to `/org/freedesktop/NetworkManager` from the interface `org.freedesktop.NetworkManager` :
```lua
local lgi = require("lgi")
local Gio, GLib = lgi.Gio, lgi.GLib

local dbus_connection, err = Gio.bus_get_sync(Gio.BusType.SYSTEM)
if not err then
    local res, err = dbus_connection:call_sync(
        "org.freedesktop.NetworkManager",
        "/org/freedesktop/NetworkManager",
        "org.freedesktop.DBus.Properties",
        "GetAll",
        GLib.Variant("(s)", {"org.freedesktop.NetworkManager"}),
        nil,
        Gio.DBusCallFlags.NONE,
        -1
    )

    print("res type: " .. res.type)
    print("res size: " .. #res)
    for k, v in res:pairs() do
        print(k,v)
    end

    print("res[1] type: ", type(res[1]))
    print("res[1] size: " .. #res[1])
    for k, v in pairs(res[1]) do
        print(k,v)
    end
end
```

And this is the result :
```
res type: (a{sv})
res size: 1.0
1	table: 0x555c648d94f0
res[1] type: table
res[1] size: 0
```

I followed [this guide](https://github.com/pavouk/lgi/blob/master/docs/variant.md) regarding GVariant datatype's manipulation, so I'm quite confident I haven't made any mistake here.
It seems to impact only dictionary data : I got this result when I subscribed to the `PropertiesChanged` signal from `org.freedesktop.DBus.Properties` :
```lua
local lgi = require("lgi")
local Gio, GLib = lgi.Gio, lgi.GLib

local dbus_connection, err = Gio.bus_get_sync(Gio.BusType.SYSTEM)
if not err then
    local function print_signal(connection, sender, path, interface, member, params)
        print("params type: " .. params.type)
        for k, v in params:pairs() do
            print(k,v)
        end
        print("params[2] type: " .. type(params[2]))
        for k, v in pairs(params[2]) do
            print(k,v)
        end
    end

    dbus_connection:signal_subscribe(
        "org.freedesktop.NetworkManager",
        "org.freedesktop.DBus.Properties",
        "PropertiesChanged",
        nil,
        nil,
        Gio.DBusSignalFlags.NONE,
        print_signal
    )
end

loop = GLib.MainLoop(nil, false)
loop:run()
```

Result :
```
params type: (sa{sv}as)
1	org.freedesktop.NetworkManager.AccessPoint
2	table: 0x55a94d0ddf80
3	lgi.rec 0x7fdea0004ea0:GLib.Variant
params[2] type: table
params type: (sa{sv}as)
1	org.freedesktop.NetworkManager.AccessPoint
2	table: 0x55a94d0dfba0
3	lgi.rec 0x7fdea0008ec0:GLib.Variant
params[2] type: table
params type: (sa{sv}as)
1	org.freedesktop.NetworkManager.IP6Config
2	table: 0x55a94d0e1770
3	lgi.rec 0x7fdea0009390:GLib.Variant
params[2] type: table
params type: (sa{sv}as)
1	org.freedesktop.NetworkManager.IP6Config
2	table: 0x55a94d0e31c0
3	lgi.rec 0x7fdea00106f0:GLib.Variant
params[2] type: table
[...]
```

Note that the first string is well displayed, but the dictionary (2nd member) is empty. This is why I think there's a bug in the way dictionaries are constructed internally with DBus.

This occurs with Lua 5.3.6 and lgi 0.9.2 on ArchLinux.

**Comment by psychon** [comment]
Well, I do not have NetworkManager and thus cannot run these examples, but according to https://github.com/lgi-devs/lgi/blob/master/docs/variant.md#data-access, I would expect some uses of `.value` in your code. However, each time I have to work with variants, my head spins, so I am not quite sure whether `.value` actually has any meaning here.

> Note that the first string is well displayed, but the dictionary (2nd member) is empty.

I am not quite sure what you are refering to, sorry.

Also, your code examples seem fishy. This code...
```lua
    print(res.type)
    print(#res)
    for k, v in pairs(res[1]) do
        print(k,v)
    end
```
...cannot produce this output:
```
res type: (a{sv})
res size: 1.0
1	table: 0x555c648d94f0
res[1] type: table
res[1] size: 0
```
That makes it quite hard to understand what is going on.

**Comment by psychon** [comment]
I experimented a bit. Can you try this `do_print` function instead?
```lua
local lgi = require("lgi")
local GLib = lgi.GLib

local v10 = GLib.Variant('(a{o(oayaysa{sd})})',
                         {{['/path/to/object1']={'/path/to/object2',
                                                 'bytestring1',
                                                 'bytestring2',
                                                 'string', { foo=4, bar=2 }}}})


local function do_print(val, prefix)
	prefix = prefix or ""
	print(prefix .. tostring(val))
	for i=1, #val do
		local child = val:get_child_value(i - 1)
		print(string.format("%s%d: %s:", prefix, i, val[i]))
		if type(val[i]) == "table" then
			do_print(child, prefix .. "    ")
		end
	end
end

do_print(v10)
```

**Comment by tlefebvr** [comment]
I edited my code from my original post : I've modified my script for a more readable output but forgot to update it in the issue.

Your function works, and my problem is fixed if I indeed use `get_child_value()` instead of indexing the variant. Thank you.
However there is something I don't understand. I cite the doc :
> `value` unpacks value of the variant.[...] tuples and dictionary entries are unpacked into Lua tables (arrays), [...] Dictionaries return proxy table which can be indexed by dictionary keys to retrieve dictionary values.

I understand that `get_child_value()` just return me the corresponding child as its `GLib.Variant` form, while `.value[]` returns me a child (in the case of a dictionary/tuple/array) to a more adequate native Lua type.
But if I can get all children using `get_child_value()` as well as those from nested tables :
```
> for k,v in pairs(v10:get_child_value(0)[1]) do print(k,v) end
1	/path/to/object1
2	table: 0x55ee1a29cac0
n	2.0

> for k,v in pairs(v10:get_child_value(0)[1][2]) do print(k,v) end
1	/path/to/object2
2	bytestring1
3	bytestring2
4	string
5	table: 0x55ee1a2a5120
n	5.0
```
Why doesn't this work when I unbox the value ?
```
> for k,v in pairs(v10.value[1][1]) do print(k,v) end
stdin:1: bad argument #1 to 'for iterator' (table expected, got nil)

> for k,v in pairs(v10.value[1]) do print(k,v) end
<nothing>
```
Is it supposed to work that way or did I miss the point ?

**Comment by psychon** [comment]
> Is it supposed to work that way or did I miss the point ?

Not really helpful, but my answer to that is: :shrug: 

I don't really know, I did not write the code and I am just trying to use it.

> Your function works, and my problem is fixed

I'll close this issue then.
